vim.keymap.set('n', '<c-k>', '<C-w>k<CR>')
vim.keymap.set('n', '<c-j>', '<C-w>j<CR>')
vim.keymap.set('n', '<c-h>', '<C-w>h<CR>')
vim.keymap.set('n', '<c-l>', '<C-w>l<CR>')
vim.keymap.set('n', '<leader>ts', ':tab split<CR>')
vim.keymap.set('n', '<leader>tc', ':tabc<CR>')
vim.keymap.set('n', '<leader><leader>', ':NvimTreeOpen<CR>')
